AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TransactionProject

  Sample SAM Template for TransactionProject

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  TransactionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: TransactionFunction
      Handler: transaction.App::handleRequest
      Runtime: java11
      Architectures:
        - arm64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
          # Database config
          DB_URL: jdbc:mysql://database-1.cbyuffbwj2x4.us-east-2.rds.amazonaws.com:3306/TransactionApp
          DB_USER: trungbui
          DB_PASS: trungbui1234
      Events:
        CreateTransaction:
          Type: Api
          Properties:
            Path: /transaction
            Method: post
        GetUserTransaction:
          Type: Api
          Properties:
            Path: /transaction/{id}
            Method: get
        GetAllTransaction:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TransactionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TransactionFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TransactionFunction.Arn
  TransactionFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TransactionFunctionRole.Arn
